# Sample Dataset
# GATATATGCATATACTT
# ATAT

# Sample Output
#2 4 10




testData = "GTTGGTAAATCTACAAGGTAAATGGTAAATCAGGTAAATCCTTGGGTAAATTGAGTGGTAAATTGGTAAATTCCGGTAAATGGGTTGGGTAAATGGTAAATAGGTAAATATGGTAAATACAGGTAAATAGGTTAGGAATGAAGAGGTAAATTGGTCTGGGTAAATGGTAAATCCGGTAGGTAAATGGTAAATTTTGGGGTAAATTGGTAAATCGAAGTTCGGTAAATCGTAAGGTAAATGGTAAATTGGTAAATTCGTCGGTAAATAGGTAAATTGGGTAAATGTTGGTAAATCAGGTAAATAGCTCACTTGTTCCGGTAAATTGGTAAATGGTAAATGCCCGGTAAATTGGTAAATACTAGGTAAATGTCGGTAAATGTGACCTTGCGCTGGGTAAATAGAATGGTAAATGGTAAATGGCCGGTAAATGGTAAATCAGCGAGGTAAATCGGTAAATATGGTAAATAGGTAAATCTGGTAAATACGGTAAATACCGACTGGTAAATGGTAAATACGCCCGTGGTAAATGAGGTAAATGCGGTAAATAGGTAAATTTTGTCCAGGGACGCCACCCAGGACAAGGTAAATACGATAAGGAGGTAAATAGGTAAATGGTAAATCGGTAAATTTGGTAAATCCGGTAAATTGGTAAATGGTAAATGGTAAATGGTAAATCGTCTAGCAATGGTAAATCTAGGTAAATGGTAAATGGTAAATCCAGGTAAATCACACAGGTAAATCACGGTAAATGTGGGTAAATAGGGTAAATGGTAAATTTTGGTAAATAAGGTAAATGGTAAATTGGTAAATAGGTAAATATCAGCCAGGTAAATGACGGGGAAGGTAAATTGGTAAATGGTAAATCGGTAAATGGGGTAAATCGCAGGTAAATTTGGGTAAATATGGTAAATGAGTAGGGGTAAATCTAAGGTAAATGGTAAATGGTAAATGGTAAATGGATGGTAAATAGGTAAATGGTAAATC"
testMotif = "GGTAAATGG"


motifLen = len(testMotif)
dataLen = len(testData)

distance = ""
seq = ""


def seqGen(x):
    seq = ""

    i = 0
    while i < motifLen: 
        # Add letters until Motiflen is reached
        seq = seq + testData[x+i] 
        i = i+1  
    return(seq)
    
    
x = 0
for i in testData:
    if dataLen > x+ motifLen:
        sequence=seqGen(x)
        print(sequence)

        
        if sequence == testMotif:
            # IF ELSE is here just for the formating
            if distance == "":
                distance = x+1
           
            else:
                distance = f"{distance} {x+1}"
    
    x=x+1

print(distance)

